Public Class PriceClass

    '[Airways Domestic]
    Public Agartala_AP As Double = 5774      '[Tripura]
    Public Aizawl_AP As Double = 6910        '[Mizoram]
    Public Amaravati_AP As Double = 6954     '[Andhra Pradesh]
    Public Bangalore_AP As Double = 7423     '[Karnataka]
    Public Bhopal_AP As Double = 6082        '[Madhya Pradesh]
    Public Bhubaneshwar_AP As Double = 7012  '[Odisha]
    Public Chandighar_AP As Double = 6984    '[Chandigarh/Punjab/Haryana]
    Public Chennai_AP As Double = 7412       '[Tamil Nadu]
    Public Daman_AP As Double = 5216         '[Dadra/NagarHaveli/Daman/Diu]
    Public Dehradun_AP As Double = 5127      '[Uttarakhand]
    Public Delhi_AP As Double = 7625         '[Delhi]  
    Public Dispur_AP As Double = 6197        '[Assam]
    Public Gandhinagar_AP As Double = 6749   '[Gujarat]
    Public Gangtok_AP As Double = 4191       '[Sikkim]
    Public Hyderabad_AP As Double = 7437     '[Telangana]
    Public Imphal_AP As Double = 4392        '[Manipur]
    Public Itanagar_AP As Double = 5186      '[Arunachal Pradesh]
    Public Jaipur_AP As Double = 7282        '[Rajasthan]
    Public Katmandu_AP As Double = 5672      '[Nepal]
    Public Kavarathi_AP As Double = 6145     '[Lakshadweep]
    Public Kohima_AP As Double = 6145        '[Nagaland]
    Public Kolkata_AP As Double = 7267       '[West Bengal]
    Public Leh_AP As Double = 4817           '[Ladakh]
    Public Lucknow_AP As Double = 6410       '[Uttar Pradesh]
    Public Mumbai_AP As Double = 7616        '[Maharastra]
    Public Panaji_AP As Double = 6138        '[Goa]
    Public Patna_AP As Double = 4613         '[Bihar]
    Public Port_Blair_AP As Double = 6333    '[Andaman Nicobar Islands]
    Public Puducherry_AP As Double = 6435    '[Puducherry]
    Public Raipur_AP As Double = 6171        '[Chhattisgarh]
    Public Ranchi_AP As Double = 4357        '[Jharkhand]
    Public Shillong_AP As Double = 4257      '[Meghalaya]
    Public Shimla_AP As Double = 5828        '[Himachal Pradesh]
    Public Srinagar_AP As Double = 6024      '[Jammu & Kashmir]
    Public Thiruvananthapuram_AP As Double = 5406  '[Kerala]

    '[Roadways]
    Public TRTC_BD As Double = 570           '[Tripura]
    Public MST_BD As Double = 690            '[Mizoram]
    Public K2_BD As Double = 695             '[Andhra Pradesh]
    Public Kempegowda_BD As Double = 745     '[Karnataka]
    Public Bhopal_BD As Double = 610         '[Madhya Pradesh]
    Public DTS_BD As Double = 710            '[Odisha]
    Public ISBT_BD As Double = 690           '[Chandigarh/Punjab/Haryana]
    Public MTC_BD As Double = 740            '[Tamil Nadu]
    Public Daman_BD As Double = 520          '[Dadra/NagarHaveli/Daman/Diu]
    Public Dehradun_BD As Double = 510       '[Uttarakhand]
    Public DTC_BD As Double = 760            '[Delhi]  
    Public DSM_BD As Double = 620            '[Assam]
    Public GSRTC_BD As Double = 675          '[Gujarat]
    Public SNT_BD As Double = 425            '[Sikkim]
    Public Hyderabad_BD As Double = 745      '[Telangana]
    Public Imphal_BD As Double = 440         '[Manipur]
    Public Blue_Hill_BD As Double = 520      '[Arunachal Pradesh]
    Public Jaipur_BD As Double = 730         '[Rajasthan]
    Public Nepal_Yatayat_BD As Double = 570  '[Nepal]
    Public NST_BD As Double = 615            '[Nagaland]
    Public WBSTC_BD As Double = 725          '[West Bengal]
    Public Leh_BD As Double = 480            '[Ladakh]
    Public Alambagh_BD As Double = 640       '[Uttar Pradesh]
    Public MSRTC_BD As Double = 760          '[Maharastra]
    Public Panaji_BD As Double = 615         '[Goa]
    Public Patliputra_BD As Double = 460     '[Bihar]
    Public Puducherry_BD As Double = 645     '[Puducherry]
    Public Raipur_BD As Double = 615         '[Chhattisgarh]
    Public Ranchi_BD As Double = 435         '[Jharkhand]
    Public Shillong_BD As Double = 425       '[Meghalaya]
    Public Shimla_BD As Double = 585         '[Himachal Pradesh]
    Public Srinagar_BD As Double = 605       '[Jammu & Kashmir]
    Public Trivandrum_BD As Double = 540     '[Kerala]

    '[Railways]
    Public Agartala_RS As Double = 370                         '[Tripura]
    Public Amaravati_RS As Double = 490                        '[Andhra Pradesh]
    Public Bairabi_RS As Double = 495                          '[Mizoram]
    Public Bangalore_RS As Double = 545                        '[Karnataka]
    Public Bhopal_RS As Double = 410                           '[Madhya Pradesh]
    Public Bhubaneshwar_RS As Double = 510                     '[Odisha]
    Public Chandighar_RS As Double = 490                       '[Chandigarh/Punjab/Haryana]
    Public Dehradun_RS As Double = 310                         '[Uttarakhand]
    Public Delhi_RS As Double = 560                            '[Delhi]
    Public Dispur_RS As Double = 420                           '[Assam]
    Public Gandhinagar_RS As Double = 475                      '[Gujarat]
    Public Rangpo_RS As Double = 225                           '[Sikkim]
    Public Hyderabad_RS As Double = 545                        '[Telangana]
    Public Imphal_RS As Double = 240                           '[Manipur]
    Public Itanagar_RS As Double = 320                         '[Arunachal Pradesh]
    Public Jaipur_RS As Double = 530                           '[Rajasthan]
    Public Kohima_RS As Double = 415                           '[Nagaland]
    Public Kolkata_RS As Double = 525                          '[West Bengal]
    Public Lucknow_RS As Double = 440                          '[Uttar Pradesh]
    Public Madgaon_RS As Double = 415                          '[Goa]
    Public Mumbai_Central_RS As Double = 560                   '[Maharastra]
    Public Nolbari_RS As Double = 225                          '[Meghalaya]
    Public Patna_RS As Double = 260                            '[Bihar]
    Public Puducherry_RS As Double = 445                       '[Puducherry]
    Public Puratchi_Thalaivar_Dr_MGR_Central_RS As Double = 540 '[Tamil Nadu]
    Public Raipur_RS As Double = 415                           '[Chhattisgarh]
    Public Ranchi_RS As Double = 235                           '[Jharkhand]
    Public Shimla_RS As Double = 385                           '[Himachal Pradesh]
    Public Srinagar_RS As Double = 405                         '[Jammu & Kashmir]
    Public Thiruvananthapuram_Central_RS As Double = 340       '[Kerala]

    Public Accom_Single As Double = 350
    Public Accom_Double As Double = 450
    Public Accom_Extra As Double = 600

    Public Flight_First_Class As Double = 1150
    Public Flight_Bussiness_Class As Double = 640

    Public Airport_Tax As Double = 303
    Public Travel_Insurance As Double = 0
    Public Ext_Luggage As Double
    Public Ext_Halts As Double


    Public Toll_Fee As Double = 120
    Public AC_Bus As Double = 300

End Class
